# Curtis Donelson, CMSC 416, Spring 2017, PA #4: Scorer subprogram
# This is part 2 of the 2-part Word Sense Disambiguation program.  This is a simple scoring subroutine
# that calculates accuracy of the output senseID's by comparing them to a key.  Overall accuracy is output.
#
# Command line input: perl scorer.pl my-line-answers.txt line-key.txt


#!/usr/local/bin/perl
use warnings;

#Variable declarations
my $lineAnswers = $ARGV[0];
my $lineKey = $ARGV[1];
my @answerArray = ();  # Array to hold answers generated by assignment program
my @keyArray = ();     # Array to hold answers provided by the key.
my @instanceCount = 0;  # Tracks total number of answers compared
my $matchCount = 0;    # Tracks number of equivalent answers

open(SRC, $lineKey) || die;
while(<SRC>) 
	{ push(@keyArray, $_); }
close (SRC);

open(SRC, $lineAnswers) || die;
while(<SRC>) 
	{ push(@answerArray, $_); }
close (SRC);

for (my $i=0; $i<=$#answerArray; $i++)
{ 
	$instanceCount++;
	if($answerArray[$i] eq $keyArray[$i])
	{ $matchCount++; }
}
$accuracy = sprintf("%.2f%%",100*$matchCount/$instanceCount);
print "\nAccuracy is $accuracy\n";